//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5420.
// 
namespace ConsumedOrders.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PrintChequesServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PrintChequesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PrintChequesService() {
            this.Url = itcClassess.GLOBAL.UrlForPrintCheques;
            //this.Url = "http://192.168.1.5:85/p/PrintChequesService.asmx";
            //this.Url = "http://192.168.1.11:6622/PrintChequesService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Print", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Print(string traderName, string storeName, string[] clientAndCostList) {
            object[] results = this.Invoke("Print", new object[] {
                        traderName,
                        storeName,
                        clientAndCostList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrint(string traderName, string storeName, string[] clientAndCostList, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Print", new object[] {
                        traderName,
                        storeName,
                        clientAndCostList}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPrint(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
